# Site settings
title: Leon Martin's Homepage
description: This page contains links to Leon Martin's web appearances.

# User settings
username: Leon Martin
user_description: Leon Martin
user_title: Research Associate & PhD Candidate
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
linkedin_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
